### ISSUE TITLE
파일명 규칙

### ISSUE THREAD

**Issue by hzoou** [push-harder-than-yesterday/computer-science#3]
1. 현재 승우님과 태형님이 올리신 파일을 보면 파일명이 한글로 되어있는 것도 있고, 영어로 되어있는 것도 있는데요. 규칙이 없는 것 같아 규칙을 정했으면 좋겠습니다.
2. 각 주제(폴더) 안에 목차를 정리한 파일이 존재하는데요. 현재 OS 의 경우에는 운영체제.md DataStructure의 경우에는 자료구조.md 로 되어있는데 현재와 동일하게 주제.md 로 갈지 아니면 목차 파일은 따로 파일명을 지정해서 갈지 논의를 해봤으면 좋겠습니다.

**Comment by hzoou** [comment]
1. 영어로 통일. 영어 자체를 결국 한글로 번역해야 하는데 부자연스러운 부분이 생길 것 같음
2. 폴더/README.md 로 작성. 목차를 담는 파일이 공통적인 이름을 가지고 있는 것이 찾기 편할 것 같음

**Comment by WooVictory** [comment]
> 1. 영어로 통일. 영어 자체를 결국 한글로 번역해야 하는데 부자연스러운 부분이 생길 것 같음
> 2. 폴더/README.md 로 작성. 목차를 담는 파일이 공통적인 이름을 가지고 있는 것이 찾기 편할 것 같음

**Comment by WooVictory** [comment]
2번처럼 폴더 아래 동일한 목차 파일 이름으로 가는게 좋아보입니다!

**Comment by hzoou** [comment]
1. 영어로 통일
2. 폴더명/README.md로 통일
