### ISSUE TITLE
CS 학습 방향성

### ISSUE THREAD

**Issue by TaeHyungK** [push-harder-than-yesterday/computer-science#6]
### 논의 배경
현재 하는 CS 학습 방식이 학습을 위한다기 보다는 open docs (?) 를 만드는 것에 가까운 것 같다.

### 해결 방안
1. 현재 방식대로 github repo에 순서대로 정리하여 작성한다.
2. 새로운 Trello 를 생성하여 각자 알아서 공부하고 학습한 내용을 공유하는 정도로만 운영한다.
3. etc..

#### ps. 추가로 다른 방안이 있으시면 자유롭게 etc에 추가해주시면 감사하겠습니다.

**Comment by WooVictory** [comment]
Trello도 좋고, Notion을 요즘 많이 쓰니까 Notion에 정리하는 것도 한번 의견을 내봅니다..!

**Comment by jongnan** [comment]
Notion 괜찮네요! 
Notion에 여러명이 정리한 것을 한번에 깃헙에 정리하는 방법도 좋은거 같네요!

**Comment by TaeHyungK** [comment]
오 Notion 도 괜찮은 것 같아요 !
Notion 잘 안써봐서 어렵던데.. 이참에 써보는 것도 괜찮은 것 같습니다..!

다만, 깃헙에 정리되어있는 것들을 트렐로든 노션이든 옮기려면 귀찮긴 하겠네요..😂

**Comment by jongnan** [comment]
md file을 노션으로 임포트하는 방법이 있지 않을까요?

**Comment by WooVictory** [comment]
notion에서 md 파일 import 가능할거에요!
